GET http://localhost:3000

### login
POST http://localhost:3000/auth/login
Content-Type: application/json

{
      "email": "shakil@gmail.com",
      "password": "123456"
}

### create user
POST http://localhost:3000/user
Content-Type: application/json

{
      "firstName": "kh",
      "lastName": "Shakil",
      "email": "shakil@gmail.com",
      "password": "123456"
}


### Send FETCH Property REQUEST
GET http://localhost:3000/property?skip=30&limit=15

### Fetch single
GET http://localhost:3000/property/15

### create property
POST http://localhost:3000/property
Content-Type: application/json

{
      "name": "Kh. shakil",
      "description": "shaki",
      "price": 12
}

### update property
PATCH  http://localhost:3000/property/1
Content-Type: application/json
access-token: 'access-token by kh'


{
      # "name": "Kh. shakil",
      # "description": "sasdf",
      "price": 9349
}


### Delete property
DELETE  http://localhost:3000/property/1


### Send FETCH SONGS REQUEST
GET http://localhost:3000/songs


### Send FETCH SINGE SONG REQUEST
GET http://localhost:3000/songs/abc

### Insert song
POST http://localhost:3000/songs
Content-Type: application/json

{
      "title": "lasting lover",
      "artists": ["siagla", "Martin"],
      "releasedDate": "2022-09-29",
      "duration": "02:34"
}
